name: Publish to NPM

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verify version matches tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          PACKAGE_VERSION=$(node -p "require('./package.json').version")

          echo "Git tag version: v$TAG_VERSION"
          echo "package.json version: $PACKAGE_VERSION"

          if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "❌ Error: Version mismatch!"
            echo "Git tag: v$TAG_VERSION"
            echo "package.json: $PACKAGE_VERSION"
            echo ""
            echo "Please update package.json version to match the tag:"
            echo "  npm version $TAG_VERSION --no-git-tag-version"
            exit 1
          fi

          echo "✅ Version matches: $PACKAGE_VERSION"

      - name: Configure NPM authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo "NPM authentication configured"
          
      - name: Install dependencies
        run: npm ci


      - name: Publish to NPM
        run: npm publish --access public
